/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import domen.Constants;
import domen.Employee;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import static java.awt.event.MouseEvent.BUTTON3;
import java.util.List;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.UIManager;
import javax.swing.plaf.FontUIResource;
import controller.EmployeeController;

/**
 *
 * @author Sofija
 */
public class EmployeesForm extends javax.swing.JFrame
{

    /**
     * Creates new form EmployeesForm
     */
    EmployeeController controller;
    TableModelEmployees modelEmployees;

    public EmployeesForm()
    {
        initComponents();
        setLocationRelativeTo(null);
        this.setTitle("Lista zaposlenih");
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.setSize(866, 600);
        UIManager.put("MenuItem.font", new FontUIResource(new Font("Arial", Font.PLAIN, 15)));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmployees = new javax.swing.JTable();
        btnChange = new javax.swing.JButton();
        btnNew = new javax.swing.JButton();
        chbDeleted = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        lblItems = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(866, 500));
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowOpened(java.awt.event.WindowEvent evt)
            {
                formWindowOpened(evt);
            }
        });

        tblEmployees.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tblEmployees.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String []
            {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblEmployees.setRowHeight(35);
        tblEmployees.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                tblEmployeesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblEmployees);

        btnChange.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnChange.setText("Izmena");
        btnChange.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnChangeActionPerformed(evt);
            }
        });

        btnNew.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnNew.setText("Novi");
        btnNew.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnNewActionPerformed(evt);
            }
        });

        chbDeleted.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chbDeleted.setText("Obrisani");
        chbDeleted.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                chbDeletedActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel1.setText("Broj stavki:");

        lblItems.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblItems.setText("jLabel2");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Zaposleni");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblItems)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(62, 62, 62))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(chbDeleted)
                        .addGap(448, 448, 448)
                        .addComponent(btnChange, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNew))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 799, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnChange, btnNew});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblItems)
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chbDeleted)
                    .addComponent(btnChange)
                    .addComponent(btnNew))
                .addGap(31, 31, 31))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnChange, btnNew});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowOpened
    {//GEN-HEADEREND:event_formWindowOpened
        modelEmployees = new TableModelEmployees();
        tblEmployees.setModel(modelEmployees);
        controller = new EmployeeController();

        if (MainForm.logged.getUserType() == Constants.USER)
        {
            btnNew.setEnabled(false);
        }

        refresh();
    }//GEN-LAST:event_formWindowOpened

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnNewActionPerformed
    {//GEN-HEADEREND:event_btnNewActionPerformed
        EmployeeForm ef = new EmployeeForm(this, rootPaneCheckingEnabled);
        ef.setVisible(true);

        if (ef.resultCode == Constants.RETURN_OK)
        {
            refresh();
        }
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnChangeActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnChangeActionPerformed
    {//GEN-HEADEREND:event_btnChangeActionPerformed
        int row = tblEmployees.getSelectedRow();
        if (row != -1)
        {
            Employee employee = modelEmployees.getZaposleni(row);
            if (chbDeleted.isSelected())
            {
                if (JOptionPane.showConfirmDialog(rootPane, "Zelite da aktivirate obrisanog zaposlenog", "Brisanje", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION)
                {

                    if (controller.undelete(employee.getId()))
                    {
                        refresh();
                    }
                }
            } else
            {
                EmployeeForm ef = new EmployeeForm(this, rootPaneCheckingEnabled, employee);
                ef.setVisible(true);

                if (ef.resultCode != Constants.RETURN_CANCEL)
                {
                    refresh();
                }

            }
        }


    }//GEN-LAST:event_btnChangeActionPerformed

    private void chbDeletedActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_chbDeletedActionPerformed
    {//GEN-HEADEREND:event_chbDeletedActionPerformed
        refresh();

        if (chbDeleted.isSelected())
        {
            btnNew.setEnabled(false);
            tblEmployees.setForeground(Color.RED);
            if(MainForm.logged.getUserType()==Constants.USER){
                btnChange.setEnabled(false);
            }
        } else
        {
            btnNew.setEnabled(true);
            btnChange.setEnabled(true);
            tblEmployees.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_chbDeletedActionPerformed

    private void tblEmployeesMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_tblEmployeesMouseClicked
    {//GEN-HEADEREND:event_tblEmployeesMouseClicked
        if (evt.getButton() == BUTTON3)
        {
            int row = tblEmployees.rowAtPoint(evt.getPoint());
            tblEmployees.setRowSelectionInterval(row, row);

            JPopupMenu menu = new JPopupMenu();

            JMenuItem izmenaMenuItem = new JMenuItem("Izmena    ");
            izmenaMenuItem.setActionCommand("Izmena");
            izmenaMenuItem.setEnabled(MainForm.logged.getUserType()==Constants.ADMINISTRATOR || !chbDeleted.isSelected());

            JMenuItem noviMenuItem = new JMenuItem("Novi     ");
            noviMenuItem.setActionCommand("Novi");
            noviMenuItem.setEnabled(MainForm.logged.getUserType()==Constants.ADMINISTRATOR && !chbDeleted.isSelected());

            JMenuItem osveziMenuItem = new JMenuItem("Osveži     ");
            osveziMenuItem.setActionCommand("Osveži");

            MenuItemListener menuItemListener = new MenuItemListener();

            izmenaMenuItem.addActionListener(menuItemListener);
            noviMenuItem.addActionListener(menuItemListener);
            osveziMenuItem.addActionListener(menuItemListener);

            menu.add(izmenaMenuItem);
            menu.add(noviMenuItem);
            menu.addSeparator();
            menu.add(osveziMenuItem);

            menu.show(tblEmployees, evt.getX(), evt.getY());

        }
    }//GEN-LAST:event_tblEmployeesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChange;
    private javax.swing.JButton btnNew;
    private javax.swing.JCheckBox chbDeleted;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblItems;
    private javax.swing.JTable tblEmployees;
    // End of variables declaration//GEN-END:variables

    private void refresh()
    {
        try
        {
            List<Employee> employees = controller.getList(chbDeleted.isSelected());

            modelEmployees.setData(employees);
            modelEmployees.fireTableDataChanged();

            lblItems.setText(String.valueOf(employees.size()));

        } catch (Exception e)
        {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }

    private class MenuItemListener implements ActionListener
    {

        @Override
        public void actionPerformed(ActionEvent e)
        {
            if (e.getActionCommand().equals("Izmena"))
            {
                btnChangeActionPerformed(e);
            }
            if (e.getActionCommand().equals("Novi"))
            {
                btnNewActionPerformed(e);
            }
            if (e.getActionCommand().equals("Osvezi"))
            {
                refresh();
            }
        }
    }
}
