/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import domen.Constants;
import domen.Task;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import static java.awt.event.MouseEvent.BUTTON3;
import java.util.List;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.UIManager;
import javax.swing.plaf.FontUIResource;
import controller.TaskController;

/**
 *
 * @author Sofija
 */
public class TasksForm extends javax.swing.JFrame
{

    /**
     * Creates new form ZadaciForm
     */
    TaskController controller = new TaskController();
    TableModelTasks modelTasks;

    public TasksForm()
    {
        initComponents();
        setLocationRelativeTo(null);
        this.setTitle("Lista zadataka");
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.setSize(866, 600);
        UIManager.put("MenuItem.font", new FontUIResource(new Font("Arial", Font.PLAIN, 15)));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblTasks = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        lblItems = new javax.swing.JLabel();
        btnChange = new javax.swing.JButton();
        btnNew = new javax.swing.JButton();
        chbDeleted = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        setSize(new java.awt.Dimension(866, 500));
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowOpened(java.awt.event.WindowEvent evt)
            {
                formWindowOpened(evt);
            }
        });

        tblTasks.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tblTasks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String []
            {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblTasks.setRowHeight(35);
        tblTasks.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                tblTasksMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblTasks);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel1.setText("Broj stavki:");

        lblItems.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblItems.setText("###");

        btnChange.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnChange.setText("Izmena");
        btnChange.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnChangeActionPerformed(evt);
            }
        });

        btnNew.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnNew.setText("Novi");
        btnNew.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnNewActionPerformed(evt);
            }
        });

        chbDeleted.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chbDeleted.setText("Obrisani");
        chbDeleted.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                chbDeletedActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Zadaci");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(chbDeleted)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnChange)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNew)
                .addGap(52, 52, 52))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 798, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblItems)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(79, 79, 79))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnChange, btnNew});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblItems)
                            .addComponent(jLabel1))
                        .addGap(4, 4, 4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnChange)
                    .addComponent(btnNew)
                    .addComponent(chbDeleted))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnChange, btnNew});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed

        TaskForm zf = new TaskForm(this, rootPaneCheckingEnabled);

        zf.setVisible(true);

        if (zf.resultCode == Constants.RETURN_OK)
        {
            refresh();
        }
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeActionPerformed
        int row = tblTasks.getSelectedRow();
        if (row != -1)
        {
            Task zadatak = modelTasks.getZadatak(row);

            if (chbDeleted.isSelected())
            {
                if (JOptionPane.showConfirmDialog(rootPane, "Zelite da aktivirate obrisani zadatak?", "Brisanje", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION)
                {

                    if (controller.undelete(zadatak.getId()))
                    {
                        refresh();
                    }
                }

            } else
            {
                TaskForm zf = new TaskForm(this, rootPaneCheckingEnabled, zadatak);

                zf.setVisible(true);

                if (zf.resultCode != Constants.RETURN_CANCEL)
                {
                    refresh();
                }
            }
        }
    }//GEN-LAST:event_btnChangeActionPerformed

    private void chbDeletedActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_chbDeletedActionPerformed
    {//GEN-HEADEREND:event_chbDeletedActionPerformed
        refresh();

        if (chbDeleted.isSelected())
        {
            tblTasks.setForeground(Color.RED);
            btnNew.setEnabled(false);
            if(MainForm.logged.getUserType()==Constants.USER){
                btnChange.setEnabled(false);
            }
        } else
        {
            tblTasks.setForeground(Color.BLACK);
            btnNew.setEnabled(true);
            btnChange.setEnabled(true);
        }
    }//GEN-LAST:event_chbDeletedActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowOpened
    {//GEN-HEADEREND:event_formWindowOpened
        modelTasks = new TableModelTasks();
        tblTasks.setModel(modelTasks);

        if (MainForm.logged.getUserType() == Constants.USER)
        {
            btnNew.setEnabled(false);
        }

        refresh();

    }//GEN-LAST:event_formWindowOpened

    private void tblTasksMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_tblTasksMouseClicked
    {//GEN-HEADEREND:event_tblTasksMouseClicked
        if (evt.getButton() == BUTTON3)
        {
            int row = tblTasks.rowAtPoint(evt.getPoint());
            tblTasks.setRowSelectionInterval(row, row);

            //JMenu origin= new JMenu();
            JPopupMenu menu = new JPopupMenu();

            JMenuItem izmenaMenuItem = new JMenuItem("Izmena     ");
            izmenaMenuItem.setActionCommand("Izmena");
            izmenaMenuItem.setEnabled(MainForm.logged.getUserType()==Constants.ADMINISTRATOR || !chbDeleted.isSelected());

            JMenuItem noviMenuItem = new JMenuItem("Novi     ");
            noviMenuItem.setActionCommand("Novi");
            noviMenuItem.setEnabled(MainForm.logged.getUserType() == Constants.ADMINISTRATOR && !chbDeleted.isSelected());

            JMenuItem osveziMenuItem = new JMenuItem("Osveži     ");
            osveziMenuItem.setActionCommand("Osveži");

            MenuItemListener menuItemListener = new MenuItemListener();

            izmenaMenuItem.addActionListener(menuItemListener);
            noviMenuItem.addActionListener(menuItemListener);
            osveziMenuItem.addActionListener(menuItemListener);

            menu.add(izmenaMenuItem);
            menu.add(noviMenuItem);
            menu.addSeparator();
            menu.add(osveziMenuItem);

            menu.show(tblTasks, evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_tblTasksMouseClicked

    private void refresh()
    {
        try
        {
            List<Task> zadaci = controller.getList(chbDeleted.isSelected());

            modelTasks.setData(zadaci);
            modelTasks.fireTableDataChanged();

            lblItems.setText(String.valueOf(zadaci.size()));
        } catch (Exception ex)
        {
            JOptionPane.showMessageDialog(rootPane, ex);
        }

    }

    private class MenuItemListener implements ActionListener
    {

        @Override
        public void actionPerformed(ActionEvent e)
        {
            if (e.getActionCommand().equals("Izmena"))
            {
                btnChangeActionPerformed(e);
            }
            if (e.getActionCommand().equals("Novi"))
            {
                btnNewActionPerformed(e);
            }
            if (e.getActionCommand().equals("Osvezi"))
            {
                refresh();
            }
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChange;
    private javax.swing.JButton btnNew;
    private javax.swing.JCheckBox chbDeleted;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblItems;
    private javax.swing.JTable tblTasks;
    // End of variables declaration//GEN-END:variables
}
