/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forms;

import domen.Constants;
import domen.Project;
import domen.Employee;
import domen.ProjectItem;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import static java.awt.event.MouseEvent.BUTTON3;
import java.util.LinkedList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import controller.ProjectController;
import controller.EmployeeController;

/**
 *
 * @author Sofija
 */
public class ProjectForm extends javax.swing.JDialog
{

    Project project;
    int projectID;
    ProjectController controller;
    EmployeeController controllerEmployee;
    List<Employee> listEmployees;
    TableModelTableItems tableModel;
    int resultCode;
    boolean wasChanges;

    public ProjectForm(java.awt.Frame parent, boolean modal)
    {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        project = new Project();
        projectID = 0;

    }

    ProjectForm(java.awt.Frame parent, boolean modal, int projectID)
    {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        this.projectID = projectID;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cmbEmployees = new javax.swing.JComboBox<>();
        btnDelete = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProjectTask = new javax.swing.JTable();
        btnChange = new javax.swing.JButton();
        btnNew = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        chbActive = new javax.swing.JCheckBox();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosing(java.awt.event.WindowEvent evt)
            {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt)
            {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Naziv");

        txtName.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                txtNameKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Vođa projekta");

        cmbEmployees.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbEmployees.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                cmbEmployeesItemStateChanged(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnDelete.setText("Obriši");
        btnDelete.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnDeleteActionPerformed(evt);
            }
        });

        btnSave.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSave.setText("Snimi");
        btnSave.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnSaveActionPerformed(evt);
            }
        });

        btnCancel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCancel.setText("Odustani");
        btnCancel.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnCancelActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(102, 102, 102), null));

        tblProjectTask.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tblProjectTask.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String []
            {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblProjectTask.setRowHeight(35);
        tblProjectTask.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                tblProjectTaskMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProjectTask);

        btnChange.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnChange.setText("Izmena");
        btnChange.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnChangeActionPerformed(evt);
            }
        });

        btnNew.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnNew.setText("Novi");
        btnNew.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnNewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnChange)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 695, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnChange)
                    .addComponent(btnNew))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnChange, btnNew});

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Status");

        chbActive.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chbActive.setText(" Aktivan");
        chbActive.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                chbActiveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(btnDelete)
                        .addGap(306, 306, 306)
                        .addComponent(btnSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbEmployees, 0, 288, Short.MAX_VALUE)
                            .addComponent(txtName)
                            .addComponent(chbActive))))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCancel, btnDelete, btnSave});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cmbEmployees, txtName});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(cmbEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(chbActive)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnCancel)
                    .addComponent(btnDelete))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cmbEmployees, txtName});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnCancel, btnDelete, btnSave});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnSaveActionPerformed
    {//GEN-HEADEREND:event_btnSaveActionPerformed
        project.setName(txtName.getText());

        project.setActive(chbActive.isSelected());

        int index = cmbEmployees.getSelectedIndex();

        Employee e = index == 0 ? null : listEmployees.get(index - 1);
        
       
        project.setLeaderID(e==null ? 0 : e.getId());
        
          
        try
        {
            controller.save(project);
            resultCode = 1;
            this.dispose();
        } catch (Exception ex)
        {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowOpened
    {//GEN-HEADEREND:event_formWindowOpened

        controller = new ProjectController();
        controllerEmployee = new EmployeeController();

        this.setTitle("Podaci o projektu");
        List<ProjectItem> items;

        try
        {
            project = controller.read(projectID);
            txtName.setText(project.getName());
            chbActive.setSelected(project.isActive());
            items = project.getItems();

        } catch (Exception ex)
        {
            items = new LinkedList<>();
            Logger.getLogger(ProjectForm.class.getName()).log(Level.SEVERE, null, ex);

        }

        try
        {
            listEmployees = controllerEmployee.getList(false);
        } catch (Exception ex)
        {
            Logger.getLogger(ProjectForm.class.getName()).log(Level.SEVERE, null, ex);
            this.dispose();
        }

        tableModel = new TableModelTableItems();
        tableModel.setData(items);

        fillEmployeesCMB();

        tblProjectTask.setModel(tableModel);

        resultCode = Constants.RETURN_CANCEL;

        setButtonns();

        wasChanges = false;
    }//GEN-LAST:event_formWindowOpened

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnDeleteActionPerformed
    {//GEN-HEADEREND:event_btnDeleteActionPerformed
        if (JOptionPane.showConfirmDialog(rootPane, "Da li ste sigurni?", "Brisanje", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION)
        {
            try
            {
                controller.delete(project.getId());
                resultCode = Constants.RETURN_DELETE;
                this.dispose();
            } catch (Exception ex)
            {
                JOptionPane.showMessageDialog(rootPane, ex);
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowClosing
    {//GEN-HEADEREND:event_formWindowClosing
        if (wasChanges)
        {
            int ret = JOptionPane.showConfirmDialog(rootPane, "Da li želite da sačuvate promene?", "PAŽNJA", JOptionPane.YES_NO_CANCEL_OPTION);

            switch (ret)
            {
                case 0:
                    btnSaveActionPerformed(null);

                    return;

                case 1:
                    this.dispose();
                    return;
                default:
                    return;
            }
        }

        this.dispose();


    }//GEN-LAST:event_formWindowClosing

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCancelActionPerformed
    {//GEN-HEADEREND:event_btnCancelActionPerformed
        formWindowClosing(null);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void txtNameKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtNameKeyTyped
    {//GEN-HEADEREND:event_txtNameKeyTyped
        wasChanges = true;
    }//GEN-LAST:event_txtNameKeyTyped

    private void cmbEmployeesItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_cmbEmployeesItemStateChanged
    {//GEN-HEADEREND:event_cmbEmployeesItemStateChanged
        wasChanges = true;
    }//GEN-LAST:event_cmbEmployeesItemStateChanged

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnNewActionPerformed
    {//GEN-HEADEREND:event_btnNewActionPerformed

        ProjectItemForm pif;
        pif = new ProjectItemForm(null, true);
        pif.setVisible(true);

        if (pif.getResultCode() == Constants.RETURN_OK)
        {
            project.getItems().add(pif.getProjectItem());
            tableModel.fireTableDataChanged();
        }
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnChangeActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnChangeActionPerformed
    {//GEN-HEADEREND:event_btnChangeActionPerformed
        int row = tblProjectTask.getSelectedRow();

        if (row != -1)
        {
            ProjectItem pi = project.getItems().get(row);

            ProjectItemForm pif;
            pif = new ProjectItemForm(null, true, pi);
            pif.setVisible(true);

            if (pif.getResultCode() == Constants.RETURN_DELETE)
            {
                project.getItems().remove(pi);
            }
            tableModel.fireTableDataChanged();

        }


    }//GEN-LAST:event_btnChangeActionPerformed

    private void chbActiveActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_chbActiveActionPerformed
    {//GEN-HEADEREND:event_chbActiveActionPerformed
        wasChanges = true;

        setButtonns();
    }//GEN-LAST:event_chbActiveActionPerformed

    private void tblProjectTaskMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_tblProjectTaskMouseClicked
    {//GEN-HEADEREND:event_tblProjectTaskMouseClicked
        if (evt.getButton() == BUTTON3)
        {
            int row = tblProjectTask.rowAtPoint(evt.getPoint());
            tblProjectTask.setRowSelectionInterval(row, row);

            //JMenu origin= new JMenu();
            JPopupMenu menu = new JPopupMenu();

            JMenuItem izmenaMenuItem = new JMenuItem("Izmena     ");
            izmenaMenuItem.setActionCommand("Izmena");
            izmenaMenuItem.setEnabled(MainForm.logged.getId() == project.getLeaderID() || MainForm.logged.getUserType() == Constants.ADMINISTRATOR);

            JMenuItem noviMenuItem = new JMenuItem("Novi     ");
            noviMenuItem.setActionCommand("Novi");
            noviMenuItem.setEnabled(MainForm.logged.getId() == project.getLeaderID() || MainForm.logged.getUserType() == Constants.ADMINISTRATOR);

            JMenuItem osveziMenuItem = new JMenuItem("Osveži     ");
            osveziMenuItem.setActionCommand("Osveži");

            MenuItemListener menuItemListener = new MenuItemListener();

            izmenaMenuItem.addActionListener(menuItemListener);
            noviMenuItem.addActionListener(menuItemListener);
            osveziMenuItem.addActionListener(menuItemListener);

            menu.add(izmenaMenuItem);
            menu.add(noviMenuItem);
            menu.addSeparator();
            menu.add(osveziMenuItem);

            menu.show(tblProjectTask, evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_tblProjectTaskMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnChange;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnSave;
    private javax.swing.JCheckBox chbActive;
    private javax.swing.JComboBox<String> cmbEmployees;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tblProjectTask;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables

    private void fillEmployeesCMB()
    {
        try
        {
            listEmployees = controllerEmployee.getList(false);
            int index = 1;

            cmbEmployees.addItem("<nije izabran>");

            for (Employee z : listEmployees)
            {
                cmbEmployees.addItem(z.toString());

                if (z.getId() == project.getLeaderID())
                {
                    cmbEmployees.setSelectedIndex(index);
                }
                index++;
            }

        } catch (Exception ex)
        {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
    }

    private void setButtonns()
    {
        if (chbActive.isSelected())
        {
            btnChange.setEnabled(true);
            btnNew.setEnabled(true);
            cmbEmployees.setEnabled(true);
            txtName.setEnabled(true);
        } else
        {
            btnChange.setEnabled(false);
            btnNew.setEnabled(false);
            cmbEmployees.setEnabled(false);
            txtName.setEnabled(false);
        }

        if (MainForm.logged.getUserType() == Constants.USER)
        {
            btnDelete.setEnabled(false);
            if (MainForm.logged.getId() != project.getLeaderID())
            {
                btnChange.setEnabled(false);
                btnNew.setEnabled(false);
                btnDelete.setEnabled(false);
                btnSave.setEnabled(false);
                chbActive.setEnabled(false);
                cmbEmployees.setEnabled(false);
                txtName.setEnabled(false);
            }
        }
    }

    private class MenuItemListener implements ActionListener
    {

        @Override
        public void actionPerformed(ActionEvent e)
        {
            if (e.getActionCommand().equals("Izmena"))
            {
                btnChangeActionPerformed(e);
            }
            if (e.getActionCommand().equals("Novi"))
            {
                btnNewActionPerformed(e);
            }
        }
    }
}
