/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forms;

import domen.Constants;
import domen.Employee;
import domen.ProjectItem;
import domen.Task;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import controller.EmployeeController;
import controller.TaskController;

/**
 *
 * @author Sofija
 */
public class ProjectItemForm extends javax.swing.JDialog
{

    /**
     * Creates new form ProjectItemForm
     */
    boolean wasChanges;
    int resultCode;
    ProjectItem projectItem;

    public ProjectItemForm(java.awt.Frame parent, boolean modal)
    {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);

        btnDelete.setVisible(false);

        projectItem = new ProjectItem();
    }

    ProjectItemForm(java.awt.Frame parent, boolean modal, ProjectItem pi)
    {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);

        btnDelete.setVisible(true);

        projectItem = pi;

    }

    public int getResultCode()
    {
        return resultCode;
    }

    public ProjectItem getProjectItem()
    {
        return projectItem;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbTasks = new javax.swing.JComboBox<>();
        cmbEmployees = new javax.swing.JComboBox<>();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtOpis = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Stavka projekta");
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosing(java.awt.event.WindowEvent evt)
            {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt)
            {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Zaposleni");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Zadatak");

        cmbTasks.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbTasks.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cmbTasksActionPerformed(evt);
            }
        });

        cmbEmployees.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbEmployees.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cmbEmployeesActionPerformed(evt);
            }
        });

        btnSave.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSave.setText("Snimi");
        btnSave.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnSaveActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnDelete.setText("Obriši");
        btnDelete.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnDeleteActionPerformed(evt);
            }
        });

        btnCancel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCancel.setText("Odustani");
        btnCancel.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnCancelActionPerformed(evt);
            }
        });

        txtOpis.setColumns(20);
        txtOpis.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtOpis.setRows(5);
        txtOpis.setEnabled(false);
        jScrollPane1.setViewportView(txtOpis);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDelete)
                            .addComponent(jLabel2))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane1)
                                    .addComponent(cmbTasks, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmbEmployees, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap(30, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSave)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCancel)
                                .addGap(33, 33, 33))))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCancel, btnDelete, btnSave});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(cmbEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbTasks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnDelete)
                    .addComponent(btnCancel))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnCancel, btnDelete, btnSave});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowOpened
    {//GEN-HEADEREND:event_formWindowOpened

        try
        {
            fillEmployeesCMB();
            fillTasksCMB();
        } catch (Exception ex)
        {
            Logger.getLogger(ProjectItemForm.class.getName()).log(Level.SEVERE, null, ex);
        }

        wasChanges = false;
    }//GEN-LAST:event_formWindowOpened

    private void cmbTasksActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cmbTasksActionPerformed
    {//GEN-HEADEREND:event_cmbTasksActionPerformed
        Task zadatak = (Task) cmbTasks.getSelectedItem();
        txtOpis.setText(zadatak.getDescription());

        wasChanges = true;
    }//GEN-LAST:event_cmbTasksActionPerformed

    private void cmbEmployeesActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cmbEmployeesActionPerformed
    {//GEN-HEADEREND:event_cmbEmployeesActionPerformed
        wasChanges = true;
    }//GEN-LAST:event_cmbEmployeesActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowClosing
    {//GEN-HEADEREND:event_formWindowClosing
        if (wasChanges)
        {
            int ret = JOptionPane.showConfirmDialog(rootPane, "Da li zelite da sacuvate promene?", "PAZNJA", JOptionPane.YES_NO_CANCEL_OPTION);

            switch (ret)
            {
                case 0:
                    btnSaveActionPerformed(null);

                    return;

                case 1:
                    resultCode = Constants.RETURN_CANCEL;
                    this.dispose();
                    return;
                default:
                    return;
            }
        }
    }//GEN-LAST:event_formWindowClosing

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCancelActionPerformed
    {//GEN-HEADEREND:event_btnCancelActionPerformed
        formWindowClosing(null);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnSaveActionPerformed
    {//GEN-HEADEREND:event_btnSaveActionPerformed
        String errors = "";
        if (cmbTasks.getSelectedIndex() == 0)
        {
            errors += "\nMorate uneti zadatak";
        }
        if (cmbEmployees.getSelectedIndex() == 0)
        {
            errors += "\nMorate uneti zaposlenog";
        }
        if (errors.equals(""))
        {
            projectItem.setTask((Task) cmbTasks.getSelectedItem());
            projectItem.setEmployee((Employee) cmbEmployees.getSelectedItem());

            resultCode = Constants.RETURN_OK;
            this.dispose();
        } else
        {
            JOptionPane.showMessageDialog(rootPane, errors);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnDeleteActionPerformed
    {//GEN-HEADEREND:event_btnDeleteActionPerformed
        if (JOptionPane.showConfirmDialog(rootPane, "Da li ste sigurni?", "Brisanje", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION)
        {

            resultCode = Constants.RETURN_DELETE;
            this.dispose();

        }
    }//GEN-LAST:event_btnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<Object> cmbEmployees;
    private javax.swing.JComboBox<Object> cmbTasks;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtOpis;
    // End of variables declaration//GEN-END:variables

    private void fillEmployeesCMB() throws Exception
    {
        List<Employee> zaposleni = new EmployeeController().getList(false);

        /*cmbZaposleni.addItem("<nije izabran>");
        cmbZaposleni.setSelectedIndex(0);*/
        cmbEmployees.addItem(new Employee());

        for (Employee z : zaposleni)
        {
            cmbEmployees.addItem(z);
            Employee e = projectItem.getEmployee();
            if (e != null && z.getId() == e.getId())
            {
                cmbEmployees.setSelectedItem(z);
            }
        }

    }

    private void fillTasksCMB() throws Exception
    {
        List<Task> zadaci = new TaskController().getList(false);

        //cmbZadatak.addItem("<nije izabran>");
        cmbTasks.addItem(new Task());

        for (Task z : zadaci)
        {
            cmbTasks.addItem(z);
            Task t = projectItem.getTask();
            if (t != null && z.getId() == t.getId())
            {
                cmbTasks.setSelectedItem(z);
                txtOpis.setText(z.getDescription());
            }
        }

    }
}
